/*
 *
 * Dashboard constants
 *
 */

export const LOAD_USER_REQUEST = 'app/Dashboard/LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'app/Dashboard/LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'app/Dashboard/LOAD_USER_FAILURE';
export const LOAD_ERROR_REQUEST = 'app/Dashboard/LOAD_ERROR_REQUEST';
export const LOAD_ERROR_SUCCESS = 'app/Dashboard/LOAD_ERROR_SUCCESS';
export const LOAD_ERROR_FAILURE = 'app/Dashboard/LOAD_ERROR_FAILURE';
export const LOAD_INFO_REQUEST = 'app/Dashboard/LOAD_INFO_REQUEST';
export const LOAD_INFO_SUCCESS = 'app/Dashboard/LOAD_INFO_SUCCESS';
export const LOAD_INFO_FAILURE = 'app/Dashboard/LOAD_INFO_FAILURE';
export const LOAD_BLOG_REQUEST = 'app/Dashboard/LOAD_BLOG_REQUEST';
export const LOAD_BLOG_SUCCESS = 'app/Dashboard/LOAD_BLOG_SUCCESS';
export const LOAD_BLOG_FAILURE = 'app/Dashboard/LOAD_BLOG_FAILURE';

export const LOAD_TOTAL_PROPERTIES_REQUEST =
  'app/Dashboard/LOAD_TOTAL_PROPERTIES_REQUEST';
export const LOAD_TOTAL_PROPERTIES_SUCCESS =
  'app/Dashboard/LOAD_TOTAL_PROPERTIES_SUCCESS';
export const LOAD_TOTAL_PROPERTIES_FAILURE =
  'app/Dashboard/LOAD_TOTAL_PROPERTIES_FAILURE';

export const LOAD_MONTH_PROPERTIES_REQUEST =
  'app/Dashboard/LOAD_MONTH_PROPERTIES_REQUEST';
export const LOAD_MONTH_PROPERTIES_SUCCESS =
  'app/Dashboard/LOAD_MONTH_PROPERTIES_SUCCESS';
export const LOAD_MONTH_PROPERTIES_FAILURE =
  'app/Dashboard/LOAD_MONTH_PROPERTIES_FAILURE';

export const LOAD_CATEGORY_PROPERTIES_REQUEST =
  'app/Dashboard/LOAD_CATEGORY_PROPERTIES_REQUEST';
export const LOAD_CATEGORY_PROPERTIES_SUCCESS =
  'app/Dashboard/LOAD_CATEGORY_PROPERTIES_SUCCESS';
export const LOAD_CATEGORY_PROPERTIES_FAILURE =
  'app/Dashboard/LOAD_CATEGORY_PROPERTIES_FAILURE';

export const LOAD_POSTS_BY_AUTHOR_REQUEST =
  'app/Dashboard/LOAD_POSTS_BY_AUTHOR_REQUEST';
export const LOAD_POSTS_BY_AUTHOR_SUCCESS =
  'app/Dashboard/LOAD_POSTS_BY_AUTHOR_SUCCESS';
export const LOAD_POSTS_BY_AUTHOR_FAILURE =
  'app/Dashboard/LOAD_POSTS_BY_AUTHOR_FAILURE';

export const LOAD_USER_SIGNUP_COUNT_REQUEST =
  'app/Dashboard/LOAD_USER_SIGNUP_COUNT_REQUEST';
export const LOAD_USER_SIGNUP_COUNT_SUCCESS =
  'app/Dashboard/LOAD_USER_SIGNUP_COUNT_SUCCESS';
export const LOAD_USER_SIGNUP_COUNT_FAILURE =
  'app/Dashboard/LOAD_USER_SIGNUP_COUNT_FAILURE';

export const LOAD_TOP_AGENT_REQUEST = 'app/Dashboard/LOAD_TOP_AGENT_REQUEST';
export const LOAD_TOP_AGENT_SUCCESS = 'app/Dashboard/LOAD_TOP_AGENT_SUCCESS';
export const LOAD_TOP_AGENT_FAILURE = 'app/Dashboard/LOAD_TOP_AGENT_FAILURE';

export const LOAD_TOP_AREAS_REQUEST = 'app/Dashboard/LOAD_TOP_AREAS_REQUEST';
export const LOAD_TOP_AREAS_SUCCESS = 'app/Dashboard/LOAD_TOP_AREAS_SUCCESS';
export const LOAD_TOP_AREAS_FAILURE = 'app/Dashboard/LOAD_TOP_AREAS_FAILURE';

export const LOAD_ACTIVE_SOLD_REQUEST =
  'app/Dashboard/LOAD_ACTIVE_SOLD_REQUEST';
export const LOAD_ACTIVE_SOLD_SUCCESS =
  'app/Dashboard/LOAD_ACTIVE_SOLD_SUCCESS';
export const LOAD_ACTIVE_SOLD_FAILURE =
  'app/Dashboard/LOAD_ACTIVE_SOLD_FAILURE';

export const LOAD_PROPERTIES_BY_PRICE_REQUEST =
  'app/Dashboard/LOAD_PROPERTIES_BY_PRICE_REQUEST';
export const LOAD_PROPERTIES_BY_PRICE_SUCCESS =
  'app/Dashboard/LOAD_PROPERTIES_BY_PRICE_SUCCESS';
export const LOAD_PROPERTIES_BY_PRICE_FAILURE =
  'app/Dashboard/LOAD_PROPERTIES_BY_PRICE_FAILURE';

export const LOAD_PENDING_PROPERTIES_REQUEST =
  'app/Dashboard/LOAD_PENDING_PROPERTIES_REQUEST';
export const LOAD_PENDING_PROPERTIES_SUCCESS =
  'app/Dashboard/LOAD_PENDING_PROPERTIES_SUCCESS';
export const LOAD_PENDING_PROPERTIES_FAILURE =
  'app/Dashboard/LOAD_PENDING_PROPERTIES_FAILURE';
