/*
 *
 * Property constants
 *
 */

export const DEFAULT_ACTION_REQUEST = 'app/Property/DEFAULT_ACTION_REQUEST';
export const DEFAULT_ACTION_SUCCESS = 'app/Property/DEFAULT_ACTION_SUCCESS';
export const DEFAULT_ACTION_FAILURE = 'app/Property/DEFAULT_ACTION_FAILURE';

export const LOAD_ALL_REQUEST = 'app/Property/LOAD_ALL_REQUEST';
export const LOAD_ALL_SUCCESS = 'app/Property/LOAD_ALL_SUCCESS';
export const LOAD_ALL_FAILURE = 'app/Property/LOAD_ALL_FAILURE';

export const LOAD_ONE_REQUEST = 'app/Property/LOAD_ONE_REQUEST';
export const LOAD_ONE_SUCCESS = 'app/Property/LOAD_ONE_SUCCESS';
export const LOAD_ONE_FAILURE = 'app/Property/LOAD_ONE_FAILURE';

export const ADD_EDIT_REQUEST = 'app/Property/ADD_EDIT_REQUEST';
export const ADD_EDIT_SUCCESS = 'app/Property/ADD_EDIT_SUCCESS';
export const ADD_EDIT_FAILURE = 'app/Property/ADD_EDIT_FAILURE';

export const DELETE_ONE_REQUEST = 'app/Property/DELETE_ONE_REQUEST';
export const DELETE_ONE_SUCCESS = 'app/Property/DELETE_ONE_SUCCESS';
export const DELETE_ONE_FAILURE = 'app/Property/DELETE_ONE_FAILURE';

export const DELETE_PROJECT_TYPE_REQUEST =
  'app/Property/DELETE_PROJECT_TYPE_REQUEST';

export const SET_ONE_VALUE = 'app/Property/SET_ONE_VALUE';
export const CLEAR_ONE = 'app/Property/CLEAR_ONE';

export const SET_QUERY_VALUE = 'app/Property/SET_QUERY_VALUE';
export const SET_INITIAL_QUERY_VALUE = 'app/Property/SET_INITIAL_QUERY_VALUE';
export const SET_FILTER_VALUE = 'app/Property/SET_FILTER_VALUE';

export const CLEAR_QUERY = 'app/Property/CLEAR_QUERY';
export const CLEAR_FILTER = 'app/Property/CLEAR_FILTER';

export const CLEAR_ERRORS = 'app/Property/CLEAR_ERRORS';

export const LOAD_ENUM_REQUEST = 'app/Property/LOAD_ENUM_REQUEST';
export const LOAD_ENUM_SUCCESS = 'app/Property/LOAD_ENUM_SUCCESS';
export const LOAD_ENUM_FAILURE = 'app/Property/LOAD_ENUM_FAILURE';

export const SET_BUILDING_VALUE = 'app/Property/SET_BUILDING_VALUE';
export const SET_LOCATION_VALUE = 'app/Property/SET_LOCATION_VALUE';
export const SET_DESCRIPTION_VALUE = 'app/Property/SET_DESCRIPTION_VALUE';

export const SET_MEDIA_VALUE = 'app/Property/SET_MEDIA_VALUE';

export const LOAD_LOCATION_REQUEST = 'app/Property/LOAD_LOCATION_REQUEST';
export const LOAD_LOCATION_SUCCESS = 'app/Property/LOAD_LOCATION_SUCCESS';
export const LOAD_LOCATION_FAILURE = 'app/Property/LOAD_LOCATION_FAILURE';

export const LOAD_STATE_REQUEST = 'app/Property/LOAD_STATE_REQUEST';
export const LOAD_STATE_SUCCESS = 'app/Property/LOAD_STATE_SUCCESS';
export const LOAD_STATE_FAILURE = 'app/Property/LOAD_STATE_FAILURE';

export const LOAD_DISTRICT_REQUEST = 'app/Property/LOAD_DISTRICT_REQUEST';
export const LOAD_DISTRICT_SUCCESS = 'app/Property/LOAD_DISTRICT_SUCCESS';
export const LOAD_DISTRICT_FAILURE = 'app/Property/LOAD_DISTRICT_FAILURE';

export const LOAD_MUNICIPALITY_REQUEST =
  'app/Property/LOAD_MUNICIPALITY_REQUEST';
export const LOAD_MUNICIPALITY_SUCCESS =
  'app/Property/LOAD_MUNICIPALITY_SUCCESS';
export const LOAD_MUNICIPALITY_FAILURE =
  'app/Property/LOAD_MUNICIPALITY_FAILURE';

export const LOAD_AREA_REQUEST = 'app/Property/LOAD_AREA_REQUEST';
export const LOAD_AREA_SUCCESS = 'app/Property/LOAD_AREA_SUCCESS';
export const LOAD_AREA_FAILURE = 'app/Property/LOAD_AREA_FAILURE';

export const SET_TAG_VALUE = 'app/Property/SET_TAG_VALUE';

export const SET_TEMP_ADDRESS = 'app/Property/SET_TEMP_ADDRESS';

export const ADD_MEDIA_REQUEST = 'app/Property/ADD_MEDIA_REQUEST';
export const ADD_MEDIA_SUCCESS = 'app/Property/ADD_MEDIA_SUCCESS';
export const ADD_MEDIA_FAILURE = 'app/Property/ADD_MEDIA_FAILURE';

export const DELETE_MEDIA_REQUEST = 'app/Property/DELETE_MEDIA_REQUEST';
export const DELETE_MEDIA_SUCCESS = 'app/Property/DELETE_MEDIA_SUCCESS';
export const DELETE_MEDIA_FAILURE = 'app/Property/DELETE_MEDIA_FAILURE';

export const LOAD_AGENTS_REQUEST = 'app/Property/LOAD_AGENTS_REQUEST';
export const LOAD_AGENTS_SUCCESS = 'app/Property/LOAD_AGENTS_SUCCESS';
export const LOAD_AGENTS_FAILURE = 'app/Property/LOAD_AGENTS_FAILURE';

export const LOAD_DEVELOPERS_REQUEST = 'app/Property/LOAD_DEVELOPERS_REQUEST';
export const LOAD_DEVELOPERS_SUCCESS = 'app/Property/LOAD_DEVELOPERS_SUCCESS';
export const LOAD_DEVELOPERS_FAILURE = 'app/Property/LOAD_DEVELOPERS_FAILURE';

export const SET_CAPTION = 'app/Property/SET_CAPTION';

export const LOAD_USER_STATUS_REQUEST = 'app/Property/LOAD_USER_STATUS_REQUEST';
export const LOAD_USER_STATUS_SUCCESS = 'app/Property/LOAD_USER_STATUS_SUCCESS';
export const LOAD_USER_STATUS_FAILURE = 'app/Property/LOAD_USER_STATUS_FAILURE';

export const SET_IS_LAND = 'app/Property/SET_IS_LAND';

export const SET_IS_PROJECT = 'app/Property/SET_IS_PROJECT';

export const ADD_FLOOR_PLAN_REQUEST = 'app/Property/ADD_FLOOR_PLAN_REQUEST';
export const ADD_FLOOR_PLAN_SUCCESS = 'app/Property/ADD_FLOOR_PLAN_SUCCESS';
export const ADD_FLOOR_PLAN_FAILURE = 'app/Property/ADD_FLOOR_PLAN_FAILURE';

export const DELETE_FLOOR_PLAN_REQUEST =
  'app/Property/DELETE_FLOOR_PLAN_REQUEST';
export const DELETE_FLOOR_PLAN_SUCCESS =
  'app/Property/DELETE_FLOOR_PLAN_SUCCESS';
export const DELETE_FLOOR_PLAN_FAILURE =
  'app/Property/DELETE_FLOOR_PLAN_FAILURE';

export const SET_FLOOR_PLAN_CAPTION = 'app/Property/SET_FLOOR_PLAN_CAPTION';

export const ADD_PAYMENT_PLAN_REQUEST = 'app/Property/ADD_PAYMENT_PLAN_REQUEST';
export const ADD_PAYMENT_PLAN_SUCCESS = 'app/Property/ADD_PAYMENT_PLAN_SUCCESS';
export const ADD_PAYMENT_PLAN_FAILURE = 'app/Property/ADD_PAYMENT_PLAN_FAILURE';

export const DELETE_PAYMENT_PLAN_REQUEST =
  'app/Property/DELETE_PAYMENT_PLAN_REQUEST';
export const DELETE_PAYMENT_PLAN_SUCCESS =
  'app/Property/DELETE_PAYMENT_PLAN_SUCCESS';
export const DELETE_PAYMENT_PLAN_FAILURE =
  'app/Property/DELETE_PAYMENT_PLAN_FAILURE';

export const SET_PAYMENT_PLAN_CAPTION = 'app/Property/SET_PAYMENT_PLAN_CAPTION';

export const ADD_PROJECT_FEATURE_REQUEST =
  'app/Property/ADD_PROJECT_FEATURE_REQUEST';
export const ADD_PROJECT_FEATURE_SUCCESS =
  'app/Property/ADD_PROJECT_FEATURE_SUCCESS';
export const ADD_PROJECT_FEATURE_FAILURE =
  'app/Property/ADD_PROJECT_FEATURE_FAILURE';

export const DELETE_PROJECT_FEATURE_REQUEST =
  'app/Property/DELETE_PROJECT_FEATURE_REQUEST';
export const DELETE_PROJECT_FEATURE_SUCCESS =
  'app/Property/DELETE_PROJECT_FEATURE_SUCCESS';
export const DELETE_PROJECT_FEATURE_FAILURE =
  'app/Property/DELETE_PROJECT_FEATURE_FAILURE';

export const SET_PROJECT_FEATURE = 'app/Property/SET_PROJECT_FEATURE';
export const SET_PROJECT_VALUE = 'app/Property/SET_PROJECT_VALUE';

export const ADD_PROJECT_TYPE_REQUEST = 'app/Property/ADD_PROJECT_TYPE_REQUEST';

// export const DELETE_PROJECT_TYPE_REQUEST =
//   'app/Property/DELETE_PROJECT_TYPE_REQUEST';
// export const DELETE_PROJECT_TYPE_SUCCESS =
//   'app/Property/DELETE_PROJECT_TYPE_SUCCESS';
// export const DELETE_PROJECT_TYPE_FAILURE =
//   'app/Property/DELETE_PROJECT_TYPE_FAILURE';

export const SET_PROJECT_TYPE = 'app/Property/SET_PROJECT_TYPE';
export const SET_PROJECT_AREA = 'app/Property/SET_PROJECT_AREA';
export const SET_PROJECT_PRICE = 'app/Property/SET_PROJECT_PRICE';

export const ADD_PROJECT_TYPE_IMAGE_REQUEST =
  'app/Property/ADD_PROJECT_TYPE_IMAGE_REQUEST';
export const ADD_PROJECT_TYPE_IMAGE_SUCCESS =
  'app/Property/ADD_PROJECT_TYPE_IMAGE_SUCCESS';
export const ADD_PROJECT_TYPE_IMAGE_FAILURE =
  'app/Property/ADD_PROJECT_TYPE_IMAGE_FAILURE';

export const DELETE_PROJECT_TYPE_IMAGE_REQUEST =
  'app/Property/DELETE_PROJECT_TYPE_IMAGE_REQUEST';
export const DELETE_PROJECT_TYPE_IMAGE_SUCCESS =
  'app/Property/DELETE_PROJECT_TYPE_IMAGE_SUCCESS';
export const DELETE_PROJECT_TYPE_IMAGE_FAILURE =
  'app/Property/DELETE_PROJECT_TYPE_IMAGE_FAILURE';

export const LOAD_AGENTS_BY_AGENCY_REQUEST =
  'app/Property/LOAD_AGENTS_BY_AGENCY_REQUEST';
export const LOAD_AGENTS_BY_AGENCY_SUCCESS =
  'app/Property/LOAD_AGENTS_BY_AGENCY_SUCCESS';
export const LOAD_AGENTS_BY_AGENCY_FAILURE =
  'app/Property/LOAD_AGENTS_BY_AGENCY_FAILURE';

export const ADD_PROJECT_TYPE_FLOOR = 'app/Property/ADD_PROJECT_TYPE_FLOOR';
export const SET_PROJECT_TYPE_FLOOR = 'app/Property/SET_PROJECT_TYPE_FLOOR';
export const DELETE_PROJECT_TYPE_FLOOR =
  'app/Property/DELETE_PROJECT_TYPE_FLOOR';
export const DELETE_PROJECT_TYPE_FEATURE_LIST =
  'app/Property/DELETE_PROJECT_TYPE_FEATURE_LIST';
export const DELETE_PROJECT_TYPE_FLOOR_IMAGE =
  'app/Property/DELETE_PROJECT_TYPE_FLOOR_IMAGE';

export const ADD_PROJECT_TYPE_FLOOR_IMAGE_REQUEST =
  'app/Property/ADD_PROJECT_TYPE_FLOOR_IMAGE_REQUEST';
export const ADD_PROJECT_TYPE_FLOOR_IMAGE_SUCCESS =
  'app/Property/ADD_PROJECT_TYPE_FLOOR_IMAGE_SUCCESS';
export const ADD_PROJECT_TYPE_FLOOR_IMAGE_FAILURE =
  'app/Property/ADD_PROJECT_TYPE_FLOOR_IMAGE_FAILURE';

export const ADD_PROJECT_TYPE_FLOOR_FEATURE =
  'app/Property/ADD_PROJECT_TYPE_FLOOR_FEATURE';
export const SET_PROJECT_TYPE_FLOOR_FEATURE =
  'app/Property/SET_PROJECT_TYPE_FLOOR_FEATURE';

export const CLEAR_PROJECT_TYPE = 'app/Property/CLEAR_PROJECT_TYPE';

export const SET_IS_BACK = 'app/Property/SET_IS_BACK';

export const AUTO_SAVE_REQUEST = 'app/Property/AUTO_SAVE_REQUEST';
export const AUTO_SAVE_SUCCESS = 'app/Property/AUTO_SAVE_SUCCESS';
export const AUTO_SAVE_FAILURE = 'app/Property/AUTO_SAVE_FAILURE';
